version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_vsualizer_app
    container_name: flask_app
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"